spring:
  application:
    name: MicroservicesConfigServer1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          clone-on-start: true

management:
  security:
    enabled: false

server:
  port: 9090
